/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#6bd8cb",
        "fortress-black": "#0B0F17",
        "surface-dim": "#0c1322",
        "secondary-container": "#29a195",
        "on-secondary": "#003732",
        "primary-fixed-dim": "#ffb3ac",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#00302b",
        "on-primary": "#680008",
        "border-subtle": "rgba(255, 255, 255, 0.08)",
        "surface-container-highest": "#2e3545",
        "security-emerald": "#10B981",
        "surface-container": "#191f2f",
        "on-error": "#690005",
        "on-secondary-fixed": "#00201d",
        "tertiary": "#9ad1cb",
        "surface-container-high": "#232a3a",
        "outline-variant": "#5c403d",
        "on-primary-fixed": "#410003",
        "primary-fixed": "#ffdad6",
        "inverse-on-surface": "#293040",
        "secondary-fixed": "#89f5e7",
        "background": "#0c1322",
        "surface-bright": "#323949",
        "inverse-surface": "#dce2f7",
        "on-surface-variant": "#e5bdb9",
        "on-surface": "#dce2f7",
        "inverse-primary": "#be0a1b",
        "surface-tint": "#ffb3ac",
        "surface-container-lowest": "#070e1d",
        "surface-container-low": "#141b2b",
        "error-container": "#93000a",
        "surface-variant": "#2e3545",
        "secondary": "#6bd8cb",
        "surface-elevated": "#1F2937",
        "on-tertiary": "#003734",
        "on-tertiary-fixed": "#00201e",
        "error": "#ffb4ab",
        "outline": "#ac8885",
        "primary": "#ffb3ac",
        "primary-container": "#d11f26",
        "on-background": "#dce2f7",
        "tertiary-fixed-dim": "#9ad1cb",
        "on-secondary-fixed-variant": "#005049",
        "on-primary-container": "#ffe8e5",
        "tertiary-fixed": "#b5ede7",
        "surface": "#0c1322",
        "on-tertiary-fixed-variant": "#144f4b",
        "on-primary-fixed-variant": "#930010",
        "tertiary-container": "#3e746f",
        "on-tertiary-container": "#bff8f1",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "margin-mobile": "16px",
        gutter: "24px",
        "margin-desktop": "64px",
        "section-gap": "120px",
        "container-max": "1440px",
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        "display-lg": ["Manrope", "sans-serif"],
        "display-lg-mobile": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
